{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.7.1/mealz-shared-analytics-4.7.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.7.1.klib",
          "url": "mealz-shared-analytics-js-4.7.1.klib",
          "size": 57184,
          "sha512": "fe4a7b92380cb97b2911915c1fdcce4f20dfe626c840e6256c2c0e6741d5cff5e469c824bc2f6d9d6dfc40f67843f84531c3ee956148c8870914804a19c956a6",
          "sha256": "be159cffd201b7c3486b05968eee75941e50156d6e803276bc0ab1fd5474a403",
          "sha1": "9c9d42d9965feae57296c12f24ae9ccad1d0cfd1",
          "md5": "d4acdf354b5ffeadc860257540716522"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.7.1.klib",
          "url": "mealz-shared-analytics-js-4.7.1.klib",
          "size": 57184,
          "sha512": "fe4a7b92380cb97b2911915c1fdcce4f20dfe626c840e6256c2c0e6741d5cff5e469c824bc2f6d9d6dfc40f67843f84531c3ee956148c8870914804a19c956a6",
          "sha256": "be159cffd201b7c3486b05968eee75941e50156d6e803276bc0ab1fd5474a403",
          "sha1": "9c9d42d9965feae57296c12f24ae9ccad1d0cfd1",
          "md5": "d4acdf354b5ffeadc860257540716522"
        }
      ]
    }
  ]
}
