{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.9.0/mealz-shared-analytics-4.9.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.9.0.klib",
          "url": "mealz-shared-analytics-js-4.9.0.klib",
          "size": 57334,
          "sha512": "8405e33bb5019b030def98c07b43bd3a689712895f162a2dd8ee6e47447fa123071e1131f79b81e0df3b5c7bbd2ee879718273511b6c7d5ce08032418a26cf7e",
          "sha256": "da6d459df3b10894c8d685a54d23e907536d439639ecfd8264dbb626d062907a",
          "sha1": "7a7452bd7f416ee9dd4e3f5823e157b94aa855b0",
          "md5": "a4ec67a399ac3879c56f647ba846706d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.9.0.klib",
          "url": "mealz-shared-analytics-js-4.9.0.klib",
          "size": 57334,
          "sha512": "8405e33bb5019b030def98c07b43bd3a689712895f162a2dd8ee6e47447fa123071e1131f79b81e0df3b5c7bbd2ee879718273511b6c7d5ce08032418a26cf7e",
          "sha256": "da6d459df3b10894c8d685a54d23e907536d439639ecfd8264dbb626d062907a",
          "sha1": "7a7452bd7f416ee9dd4e3f5823e157b94aa855b0",
          "md5": "a4ec67a399ac3879c56f647ba846706d"
        }
      ]
    }
  ]
}
