{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-1.0.0.klib",
          "url": "mealz-shared-analytics-js-1.0.0.klib",
          "size": 47310,
          "sha512": "90a64b9f41da9295c946366670a116553a50d9d952e00012330cc1dcf0ab9e6fb2ab066f8550e9fe6327ad535366e2874fd5170a82fa9b6377478b86c717a507",
          "sha256": "50b8b51fc14fe58114f06727fbe725ff1e61a967574166d96d10d6807aba4ff4",
          "sha1": "f69de4d1f0410f333bbe966687e26b660856a5b8",
          "md5": "7c737efd9dfbc5125fc3e5a9fc2d66dd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-1.0.0.klib",
          "url": "mealz-shared-analytics-js-1.0.0.klib",
          "size": 47310,
          "sha512": "90a64b9f41da9295c946366670a116553a50d9d952e00012330cc1dcf0ab9e6fb2ab066f8550e9fe6327ad535366e2874fd5170a82fa9b6377478b86c717a507",
          "sha256": "50b8b51fc14fe58114f06727fbe725ff1e61a967574166d96d10d6807aba4ff4",
          "sha1": "f69de4d1f0410f333bbe966687e26b660856a5b8",
          "md5": "7c737efd9dfbc5125fc3e5a9fc2d66dd"
        }
      ]
    }
  ]
}
