{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-metadata-4.5.0.jar",
          "url": "mealz-shared-analytics-4.5.0.jar",
          "size": 11173,
          "sha512": "e71f7dfa920aca9282aa6859e5f9a9a5bd15d3b9eff8c2d0469e2237523ece7df7d5413d3094e107e201ba9c1bd728517563edb6167bcbbcf6f1c733cea94168",
          "sha256": "fba5294fc47ee471af28d6cbb021440ecc3241c8ebefb3c363a95472d3d4530d",
          "sha1": "5ed6351334cf48ef5de3bf626f19a3535bbd57b2",
          "md5": "53662a1e329d6c06cf55a7dab9b6d5c5"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android-debug/4.5.0/mealz-shared-analytics-android-debug-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android-debug",
        "version": "4.5.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android-debug/4.5.0/mealz-shared-analytics-android-debug-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android-debug",
        "version": "4.5.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android/4.5.0/mealz-shared-analytics-android-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android",
        "version": "4.5.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android/4.5.0/mealz-shared-analytics-android-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android",
        "version": "4.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosarm64/4.5.0/mealz-shared-analytics-iosarm64-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosarm64",
        "version": "4.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosarm64/4.5.0/mealz-shared-analytics-iosarm64-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosarm64",
        "version": "4.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iossimulatorarm64/4.5.0/mealz-shared-analytics-iossimulatorarm64-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iossimulatorarm64",
        "version": "4.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iossimulatorarm64/4.5.0/mealz-shared-analytics-iossimulatorarm64-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iossimulatorarm64",
        "version": "4.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosx64/4.5.0/mealz-shared-analytics-iosx64-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosx64",
        "version": "4.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosx64/4.5.0/mealz-shared-analytics-iosx64-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosx64",
        "version": "4.5.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-js/4.5.0/mealz-shared-analytics-js-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-js",
        "version": "4.5.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-js/4.5.0/mealz-shared-analytics-js-4.5.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-js",
        "version": "4.5.0"
      }
    }
  ]
}
