{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.0.0/mealz-shared-analytics-4.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.0.0.klib",
          "url": "mealz-shared-analytics-js-4.0.0.klib",
          "size": 52430,
          "sha512": "35d4e7cb830ae2a64d2dae0153f42ff206c82a96d005b23257c164054de7176ce9659eef20d7744d926443e235f12bad87be79594ce1d255be4e1301c1081e4b",
          "sha256": "36be2af4674bb3df787f16cfac4b25aa87d5c84f877e10c812cca3cfe151af8b",
          "sha1": "f9d0425570327ade9ae5b99ef614e7f52f24d9cd",
          "md5": "96dce500b0463f54134af27ccbc1f565"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.0.0.klib",
          "url": "mealz-shared-analytics-js-4.0.0.klib",
          "size": 52430,
          "sha512": "35d4e7cb830ae2a64d2dae0153f42ff206c82a96d005b23257c164054de7176ce9659eef20d7744d926443e235f12bad87be79594ce1d255be4e1301c1081e4b",
          "sha256": "36be2af4674bb3df787f16cfac4b25aa87d5c84f877e10c812cca3cfe151af8b",
          "sha1": "f9d0425570327ade9ae5b99ef614e7f52f24d9cd",
          "md5": "96dce500b0463f54134af27ccbc1f565"
        }
      ]
    }
  ]
}
