{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.13.0/mealz-shared-analytics-4.13.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.13.0.klib",
          "size": 58381,
          "sha512": "9332a88a0f3cc46157734ed110da781c323d09dafa36a2f9622a1e73321b349d9c2faffd7b23d482385b23cfa5fbbf3da428990062fc6af8cbe8be72a20b2f16",
          "sha256": "81cfe9de99af32e2843ccdcf2d4b542f050d5d9663cfa990bafd233c7eb40ab8",
          "sha1": "1a35aeb51fa11deb139802b89a9b262f60b980b4",
          "md5": "dabf58073355c74ae088bead3980f5da"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.13.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.13.0-metadata.jar",
          "size": 4925,
          "sha512": "8ffe3f54b9d0aa91d0a467eca7736139f776b413155dea3bce576aaaa161a44c0951aaab60f8d3ffc8611c59058072d6f82aa61536ef2d4b87e56c7a9f37993a",
          "sha256": "031c2a3962923c72284554a2922158849cb22f63a4eeea603ab2bf051d944f79",
          "sha1": "696425bb2dc82833b480a113e78434bf61fe6d84",
          "md5": "8c211803aa5c3a8bcbe05e64bce506a1"
        }
      ]
    }
  ]
}
