{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.13.0/mealz-shared-analytics-4.13.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.13.0.klib",
          "size": 58398,
          "sha512": "b14d8d22fb0f96ef45b6797fcf2568310bc9ee0aec476463707ce804ffac38b33e4ababfa8bf6e0bed40f164f6813e76ae0b58a87d1a0217ba491051d5990841",
          "sha256": "c10997664750c0c5520ecad284ccf4d7589065912ab761921fb15664a2937f4d",
          "sha1": "037ae9654b9413a6cb9613850b5dbd5c753b351a",
          "md5": "ceddadc10dc6d4bb4ac1968ef3f07a18"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.13.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.13.0-metadata.jar",
          "size": 4925,
          "sha512": "8ffe3f54b9d0aa91d0a467eca7736139f776b413155dea3bce576aaaa161a44c0951aaab60f8d3ffc8611c59058072d6f82aa61536ef2d4b87e56c7a9f37993a",
          "sha256": "031c2a3962923c72284554a2922158849cb22f63a4eeea603ab2bf051d944f79",
          "sha1": "696425bb2dc82833b480a113e78434bf61fe6d84",
          "md5": "8c211803aa5c3a8bcbe05e64bce506a1"
        }
      ]
    }
  ]
}
