{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.0.0/mealz-shared-analytics-4.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.0.0.klib",
          "size": 53031,
          "sha512": "00e2cf03c750358074a72dd31b73ad28ef5c6846e92c3dd6908cfab5ea3dbca09c063898e95f9c970c0a1ddb457a7ad0d15b74d0533bbef7df1b1df3e8510680",
          "sha256": "417eb580a7a538dc10c8ed48e3c209e9ff83d34bcb5f8196707b0574f8354d3d",
          "sha1": "26a957f058fcc5680c4079f938919c3f3b2b95ea",
          "md5": "c0584dadb2d9688bf0c9032c92cf944d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.0.0-metadata.jar",
          "size": 4911,
          "sha512": "32e5e182b681d8384f4ce54b3a9d3a1db9b52fa3885dbd8edaeb6203d250de4170aeff1a9ba36f470afc3d40f3b382e5600c53e0b16bf978910119170221c6d1",
          "sha256": "bc560061112b9e71e05a03bc888a120c92fd24190311867ce5f37372a237ac8c",
          "sha1": "b646657ef52dd719bf21fe12fa09a1cd12e007ef",
          "md5": "c121be0b5dabcca675a41de4f34ebff3"
        }
      ]
    }
  ]
}
