{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.0/mealz-shared-analytics-4.3.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.3.0.klib",
          "size": 54255,
          "sha512": "e5010d2ae3c3d957696f9cd364b3efc89fc1a2018dc44c167ab9bfe98af39641ccb045ae4f1a5f96b8daea1784c56a2d1c8a19ca905b67a0bb3acecdb31c0a16",
          "sha256": "f56578b65b0d9b8791b8a7203b7718a37f93cd827153ba142b6a1fbaeabad375",
          "sha1": "b79c7ed6947edf176bf4e713df0bb3004708101a",
          "md5": "04b92dc9b36923d55e3485a54a79cce8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.3.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.3.0-metadata.jar",
          "size": 4911,
          "sha512": "3f0250da00024afa7b77062ec9ccc2b47c2a1578c51300993266530dfe8f1d24f22a0d1c40d129ec50b4940f4b0a7aded419ceed681b2a1e6e5cbd18388ebe4b",
          "sha256": "4b0a53df87a6508c417b38480d4264c51409d5789c2919833c975427f8ab2879",
          "sha1": "07e3befb69c2fa43cf7d86c1fefda21f5787ed52",
          "md5": "3c73e3172726b5046055707344e17cbc"
        }
      ]
    }
  ]
}
