{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.11.0/mealz-shared-analytics-4.11.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.11.0.klib",
          "size": 58460,
          "sha512": "1842a89b0d5aaa33b731764a2610b61ddd82c09184184bd8d8866e8da6fd58c478c9b00835bff6213801c8eeb6e6cffdddab2a4c5cd414563b480add6be38eb1",
          "sha256": "ad4308b858784fb394fac5c0e1c8a657954bb58e3a6538fb6ccce608358a83a5",
          "sha1": "9480a3cf934d6fc2abbf97c33544ab3392c1b7ff",
          "md5": "ce1dd328737210ecbc5d6bef812722f3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.11.0-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.11.0-metadata.jar",
          "size": 4925,
          "sha512": "f348edd944e9e221e9a98d77c96cb11c08ff8d1b72fbbdf0a511697e1a306ef9e99df63d53e20f9b251536bf3c0b21979d15af258b60b1b07dd1c14d6ca48101",
          "sha256": "6a08d839cd591b332ed00dad302b26162b0b3b2b02f4478fa794b057dda3aa04",
          "sha1": "079834ceb74adb1e276469d67a4006e1f7a8d5ca",
          "md5": "f4d9219a2cb0c821f4268b2b76ea8fc8"
        }
      ]
    }
  ]
}
