{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.13.1/mealz-shared-analytics-4.13.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.13.1.klib",
          "size": 58522,
          "sha512": "9589f9fde202ce015414f99f44f6f88bc6d58b1d310bcfeb6d9d7cdf601a5158fbbf83b34e8de5dbbba3905bd08bda74b3c420d8722ea68d88b334bec4d73e2d",
          "sha256": "717f042a9ada5147b9a869c56fcf6080a65287a990a8ff794882c6fcf03c4411",
          "sha1": "b7c56d8e44d96f76945e93d24608fc626b83eca0",
          "md5": "ffc1f52c62560760688553df373ef1a1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.13.1-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.13.1-metadata.jar",
          "size": 4925,
          "sha512": "e46558258029236bca62e382977285e2fb61d49d7a62ea0f1674193eca2efbec263fc705549c825654c6dfd2379ccbbf27abf297ecfa5ae3417305cc0728dcd1",
          "sha256": "57399955aabc34f3956623307b0f0a0e7a28eba3e359ca149e8840445b33140f",
          "sha1": "917b12eaf31f2f581b28a8da04d04526c14d081c",
          "md5": "d0b660ea26e0d1f778d52d3df93cad2d"
        }
      ]
    }
  ]
}
