{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/2.0.0/mealz-shared-analytics-2.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-2.0.0.klib",
          "size": 57065,
          "sha512": "1e7b8f5eae9331d7f7871cf6d6b6ca363f6f71ef813a90049689408ed607bb884f7f2eac31e754b3b3ab4f3bba3d6c5dfd023e9e9b3c700b9d7e570b39beba96",
          "sha256": "2bb9d794e5a2fec954e1b4ec4dc202ad42f4a57027e138ce517965406a34c4a1",
          "sha1": "affa9a7165790f4abaa454396260002b8f6e503e",
          "md5": "432f4b4af623c065b6d3cf95399dcc1c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-2.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-2.0.0-metadata.jar",
          "size": 3220,
          "sha512": "710720cf639bbd33d0c3020b2772f103d22793a95def1f45bd2a2c8d0c2a2627e39f68b3144eb355f34a7ca908da6c97afaae43381be3ef7d40879b3749aab3f",
          "sha256": "b4a82844e6f3045672b2dcca6b90feef2945a618b9d4c8d3e1873fc7eeef39d8",
          "sha1": "c5529f38fb555419cace3bdf3b755d98f49063aa",
          "md5": "10d5f2cbba9f50f1773e88ba21423230"
        }
      ]
    }
  ]
}
