{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.1.0/mealz-shared-analytics-4.1.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.1.0.klib",
          "size": 53109,
          "sha512": "eb9cc20429eb5cf02c2aad4efa09944eeb2bccf0c3f6c4636ef4235955c9735a4c40fe9856cbd8afeef093cf25b14ed48d9b63614ab015707cdd4651c8460f74",
          "sha256": "ee05098f2cc5d82900d7294420f3c99c35ac0cb22543e5f7a43de34997647bbb",
          "sha1": "3a1b7906be4cad57a54a8eda0151a90b60f29658",
          "md5": "76585cb23a6ad336ea7d9cc963865ce5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.1.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.1.0-metadata.jar",
          "size": 4911,
          "sha512": "26c5d444f84bbb4fe828b535a749ff246bf763ee892d30f0607448c4d117b02d79a333379a7c0d8b1e95addb47e7ad71dd4824a07d7308e4f45902e08a8f04d1",
          "sha256": "fec2bda8d5ef5549512f533164fda26ae858a34ba8f80fc355ac0962367684ee",
          "sha1": "c1bcd39553cd9f555d79bcb944631c1301cca1d1",
          "md5": "b413207a0114d9c6b634a012b3d67d96"
        }
      ]
    }
  ]
}
