{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.4.1/mealz-shared-analytics-4.4.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.4.1.klib",
          "url": "mealz-shared-analytics-js-4.4.1.klib",
          "size": 54188,
          "sha512": "42ad2d59099dd0f87e9dad80b37181fa0811b90ca89e614e12f2c80d2753091e67e01d2cf3f99879075dedbd5f7ba8abf4681b451dc58fbc4f03fb04decc8b22",
          "sha256": "9976464f26199c01332d14a956d8e3fbce3482c399041bd50a4755e2fa329d38",
          "sha1": "6605a77d3df0e4c5007e6d28c083429efc16571e",
          "md5": "2e8db9ad7059a4b802f14b3d1b723eed"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.4.1.klib",
          "url": "mealz-shared-analytics-js-4.4.1.klib",
          "size": 54188,
          "sha512": "42ad2d59099dd0f87e9dad80b37181fa0811b90ca89e614e12f2c80d2753091e67e01d2cf3f99879075dedbd5f7ba8abf4681b451dc58fbc4f03fb04decc8b22",
          "sha256": "9976464f26199c01332d14a956d8e3fbce3482c399041bd50a4755e2fa329d38",
          "sha1": "6605a77d3df0e4c5007e6d28c083429efc16571e",
          "md5": "2e8db9ad7059a4b802f14b3d1b723eed"
        }
      ]
    }
  ]
}
