{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.1.1/mealz-shared-analytics-4.1.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.1.1.klib",
          "url": "mealz-shared-analytics-js-4.1.1.klib",
          "size": 52489,
          "sha512": "70d79b64acde1dcbc36a9b97f16aa9415fd3c12c2793e506d8a2f015cf3df6e745de3c0e90d3e244fe60ac663fb105c52ea1fe61760492bdbfabcd4f636f5333",
          "sha256": "bd0fdae6fe2913cd361526508b575d6f0ba756b0997a7f0548ab0f2d70cbb482",
          "sha1": "24a024b927ae824ae713dbe3d7cae48ab899b2fb",
          "md5": "f72b02511f44a011547642093405bd7b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.1.1.klib",
          "url": "mealz-shared-analytics-js-4.1.1.klib",
          "size": 52489,
          "sha512": "70d79b64acde1dcbc36a9b97f16aa9415fd3c12c2793e506d8a2f015cf3df6e745de3c0e90d3e244fe60ac663fb105c52ea1fe61760492bdbfabcd4f636f5333",
          "sha256": "bd0fdae6fe2913cd361526508b575d6f0ba756b0997a7f0548ab0f2d70cbb482",
          "sha1": "24a024b927ae824ae713dbe3d7cae48ab899b2fb",
          "md5": "f72b02511f44a011547642093405bd7b"
        }
      ]
    }
  ]
}
