{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.7.1/mealz-shared-analytics-4.7.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.7.1.klib",
          "size": 58204,
          "sha512": "66d018d710480692bca19aced1f4d79c8276cea55b1934dd10daa0972c7f7da1af56a696ce2a56d31f8e7c1d24f6605200cf38611a776a7eb9c44ae65a5bde46",
          "sha256": "d389b1516d587d8f958239a044289f4b02cef6a52b5b0976c6f3172055f31666",
          "sha1": "e6ca86adc02116124c9cf15fe30479d5c2c7e301",
          "md5": "4ead1f9fe300da4e2ca1128faf17cb3e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.7.1-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.7.1-metadata.jar",
          "size": 4925,
          "sha512": "1c0ca3ee27e2283290be3a2a055e6aaacbb494807b39093127d20ae20ef3705d4e4deaa0014dabd3fdf00d061f869ffc7444da29507d2a7a1e429dbc6c9b92c4",
          "sha256": "30e6276ddb903481b61a6ddb603f4505e285f1887db7f8e7f84815d420d4cb3b",
          "sha1": "6f8a28a5692524ffb99e38fec59fd79d6d69f924",
          "md5": "4a7538da5e1960c63f4b4184fa06e675"
        }
      ]
    }
  ]
}
