{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.1.0/mealz-shared-analytics-4.1.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.1.0.klib",
          "url": "mealz-shared-analytics-js-4.1.0.klib",
          "size": 52491,
          "sha512": "22fb6487bac2545c4e1541d8e70f070813e168f00e66af0525eaf1fe8fabb23a730ec628b75e78488da3b085c60709de1b16a45ae2b8f60638da53754436dd96",
          "sha256": "d47a9be15533374b69d347319294df47cfcd7c23921f4d9d26a10ffe993b8606",
          "sha1": "d8cdb0c339e57c9f661b91cb020758e1b6e86f1d",
          "md5": "f86ed7d654bf34ccbdca33fe3e1e4470"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.1.0.klib",
          "url": "mealz-shared-analytics-js-4.1.0.klib",
          "size": 52491,
          "sha512": "22fb6487bac2545c4e1541d8e70f070813e168f00e66af0525eaf1fe8fabb23a730ec628b75e78488da3b085c60709de1b16a45ae2b8f60638da53754436dd96",
          "sha256": "d47a9be15533374b69d347319294df47cfcd7c23921f4d9d26a10ffe993b8606",
          "sha1": "d8cdb0c339e57c9f661b91cb020758e1b6e86f1d",
          "md5": "f86ed7d654bf34ccbdca33fe3e1e4470"
        }
      ]
    }
  ]
}
