{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.12.0/mealz-shared-analytics-4.12.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.12.0.klib",
          "size": 58386,
          "sha512": "1ee21f16f6f9f72d33be596a693ffdb1f4d018e88624eed92c8947d2c5e46b601e636cb355870edc7fe68006a4fc1835f7bbdb6343baa99e64428e8e02ced5ad",
          "sha256": "38bc6f1daa564c9640e5fd2fc5f0ee62bdfea677eaf1f0e39e80893b8cd4f9c2",
          "sha1": "a2c96b07ae161edb51496668538167f46b0707e3",
          "md5": "c48a39893f6a84f1b6c9aad7388bc40b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.12.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.12.0-metadata.jar",
          "size": 4925,
          "sha512": "cf44dbae44a19aab3a0bc06986dafe1f08aac193870e851c721561f82f3497fe81611661cfae3e7a1ca10073e592e857e767247da47077fcca347dee18956868",
          "sha256": "2435d0648fcc1e7847234e27931141bb649250fa69c39059f0d216c02359a0b6",
          "sha1": "8b153152a1ef6706112cbbe2c30cb7667cedaf29",
          "md5": "47deadf3fad7a2097aeb247dd38ff109"
        }
      ]
    }
  ]
}
