{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-1.0.0.klib",
          "size": 54636,
          "sha512": "b9bcf3fbd31b4ace4c6e35dc1da376b2991cd09aacca483fb6181f349de688b6e3a069ef09bf7e195a18c7724bc2daaa3adab612726bf036aaa8b20b5fb3d1c5",
          "sha256": "67898e8f6e44765ddc326e9433abe70c3ba86b8333d0d48d70f590a3f1bb78e6",
          "sha1": "cab60d667ce86375d464852ee50f7ab74771dff7",
          "md5": "bc1b92e825a902f3abcf717b8685c94f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-1.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-1.0.0-metadata.jar",
          "size": 3220,
          "sha512": "b7a049ce305d68600493b573c15de4437a8f1434d4f98984cc3c72f527064341e505e8f94cf1d279c1bbc7563a4b3f838a59658d719ca6a2a57f5e42b6f3efc4",
          "sha256": "3d9dde84dbda62e3692088d900a2bd12f1a191914c451073d7d723b937e95f6e",
          "sha1": "f466d9febb3d3f87e4d958712b36121dd7d06cf8",
          "md5": "03fa1866db2f3a7eff9843e0c1923522"
        }
      ]
    }
  ]
}
