{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.11.0/mealz-shared-analytics-4.11.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.11.0.klib",
          "url": "mealz-shared-analytics-js-4.11.0.klib",
          "size": 57441,
          "sha512": "af9e62545936c3ea8d3f0b8bce05b116925d4159130b9bb15900573f4d37104b6ec19e02c9841775c86c851eb9159f921f32279375a361bb64a584ffc92be31c",
          "sha256": "e760c3fc910ead693163e4c1b2bf507f4139a4bb5b29caf23ba96bf130f89b60",
          "sha1": "27168f6727b87a0513f0d3e6b4fa8d9958b9ca91",
          "md5": "228319bc0977a3a05c5d8046193a10c8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.11.0.klib",
          "url": "mealz-shared-analytics-js-4.11.0.klib",
          "size": 57441,
          "sha512": "af9e62545936c3ea8d3f0b8bce05b116925d4159130b9bb15900573f4d37104b6ec19e02c9841775c86c851eb9159f921f32279375a361bb64a584ffc92be31c",
          "sha256": "e760c3fc910ead693163e4c1b2bf507f4139a4bb5b29caf23ba96bf130f89b60",
          "sha1": "27168f6727b87a0513f0d3e6b4fa8d9958b9ca91",
          "md5": "228319bc0977a3a05c5d8046193a10c8"
        }
      ]
    }
  ]
}
