{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.0/mealz-shared-analytics-4.3.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.3.0.klib",
          "size": 54238,
          "sha512": "e85e412953752fc5568733ed5fdbb8d209fea8a489856250596db9d69cce2f1d4535f8f2b88d473eabf72b0a4b48179474973bf13b3aa56794b58a1c8316b15b",
          "sha256": "cd5a695a56f8efdd7fdb837553d53415969a087d36a2502888ba526ed9e8e7d0",
          "sha1": "15d0d80c528f30c7e2cb37633466b87a4799fcda",
          "md5": "2a5353f5b4f7ee55a2bbd8e2b80d2927"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.3.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.3.0-metadata.jar",
          "size": 4911,
          "sha512": "3f0250da00024afa7b77062ec9ccc2b47c2a1578c51300993266530dfe8f1d24f22a0d1c40d129ec50b4940f4b0a7aded419ceed681b2a1e6e5cbd18388ebe4b",
          "sha256": "4b0a53df87a6508c417b38480d4264c51409d5789c2919833c975427f8ab2879",
          "sha1": "07e3befb69c2fa43cf7d86c1fefda21f5787ed52",
          "md5": "3c73e3172726b5046055707344e17cbc"
        }
      ]
    }
  ]
}
