{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.7.2/mealz-shared-analytics-4.7.2.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.7.2.klib",
          "size": 58135,
          "sha512": "3ce29afef8794729af9b6b808db606f8231f5f33196dbd41ec5fcb3a801421100f9ecee976bf37960517e27fa8dd9650273216572c2d1ca78a6872bd77d00164",
          "sha256": "b635176584ad7a105524435f6ca5bd72e7eac23cd9e7f9e72794de4a05b7c340",
          "sha1": "ba529eda0c64c4f33767d4e9a8d463b4d8cc74bf",
          "md5": "5cdc68f2a8743a12d82dbb0fa212f201"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.7.2-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.7.2-metadata.jar",
          "size": 4925,
          "sha512": "5f4e41c66fa8463e7de6521887ae20213b8c63b5bae218f3539eeb08fe076f046132fd6292dd0909e9bc548e45e7cc84fd06391840c55b33e555fbb196e43d7c",
          "sha256": "d7d0ef3fdad58468bdb896a2cfdf2635453cbd34473561f3e91305f2964f520f",
          "sha1": "30e479124c16bd5d3703ef6f16e6f9b5d27d3771",
          "md5": "42be808956f0487c214742cf074af47c"
        }
      ]
    }
  ]
}
