{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.9.0/mealz-shared-analytics-4.9.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-debug.aar",
          "url": "mealz-shared-analytics-android-debug-4.9.0.aar",
          "size": 51139,
          "sha512": "ea1061b4d60579bfa30f55d6a2e008c049603d216374e9b418143ffffe301eeb6e250af79884288b86a36ed00b71bebe0fa6cac9f784b8507fe0c53efaa63557",
          "sha256": "7e553c9df0618a2a4de15aa7e05e3c2e1edd4db8a7d0e6f6b6af73f4b7826385",
          "sha1": "4c64b3ef45d505bc6c412a4a9ebc886502f5e3c3",
          "md5": "69243c7f6f5522fcee5bfd4ec561c25b"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-debug.aar",
          "url": "mealz-shared-analytics-android-debug-4.9.0.aar",
          "size": 51139,
          "sha512": "ea1061b4d60579bfa30f55d6a2e008c049603d216374e9b418143ffffe301eeb6e250af79884288b86a36ed00b71bebe0fa6cac9f784b8507fe0c53efaa63557",
          "sha256": "7e553c9df0618a2a4de15aa7e05e3c2e1edd4db8a7d0e6f6b6af73f4b7826385",
          "sha1": "4c64b3ef45d505bc6c412a4a9ebc886502f5e3c3",
          "md5": "69243c7f6f5522fcee5bfd4ec561c25b"
        }
      ]
    }
  ]
}
