{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/3.0.0/mealz-shared-analytics-3.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-3.0.0.klib",
          "size": 53481,
          "sha512": "4e8823ec1be453c8c4ae1be3f0f6fa9cdf32de3c8e12ad6c5d0a7865c0394841c19e6e646be224c9fe9ae63ffecf07002b2bfaffd125f96e462be4fed868da85",
          "sha256": "aea0d731309d2e51caeeb5946adafe5b813d30a9f81038913cefaaa5b1369b84",
          "sha1": "4fbcabc9d3ff63b1d7a7c0c6c0ec5cc2693e3602",
          "md5": "fa4a7a563bdb57733aad4f89e526c0f9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-3.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-3.0.0-metadata.jar",
          "size": 4911,
          "sha512": "2a3fe666c6ce526e265bee3b35ab640fa099ce1bb4bccbcce0ff5d204f18995a3016ccafbf33b2a991a919b3a563d2ed4d34f679cc0abfb4fd249fe6210a3c80",
          "sha256": "ef520c24f781d11e4eff9bce2d030033322bba3379fd90f8c2e196b5bd34ca8c",
          "sha1": "126b49aab20c5b02cb232a6ece63525b47bd5e44",
          "md5": "eecbc1133bafc5747590ed59971027af"
        }
      ]
    }
  ]
}
