{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.13.1/mealz-shared-analytics-4.13.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.13.1.klib",
          "size": 58625,
          "sha512": "926d891716361550e0946a8aa95f8fdd57654c7aedb741aa518a32973f6d4808ee9107ff8ace3fa72c9b28c6a5a1c7e7796f3c613ad33e5b72dbc685504b50e3",
          "sha256": "a1a1da5a994de6581863acc2c34a2792a2e4fd6c852c8251f3f0b741d870d5dc",
          "sha1": "3eff989aa51e365c8b8fdb19f88d70c6adf17df9",
          "md5": "c5a738ae641486b87ff2ffa14a029747"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.13.1-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.13.1-metadata.jar",
          "size": 4925,
          "sha512": "e46558258029236bca62e382977285e2fb61d49d7a62ea0f1674193eca2efbec263fc705549c825654c6dfd2379ccbbf27abf297ecfa5ae3417305cc0728dcd1",
          "sha256": "57399955aabc34f3956623307b0f0a0e7a28eba3e359ca149e8840445b33140f",
          "sha1": "917b12eaf31f2f581b28a8da04d04526c14d081c",
          "md5": "d0b660ea26e0d1f778d52d3df93cad2d"
        }
      ]
    }
  ]
}
