{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.2.0/mealz-shared-analytics-4.2.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-debug.aar",
          "url": "mealz-shared-analytics-android-debug-4.2.0.aar",
          "size": 46746,
          "sha512": "7db562eee8d3801495118502b212bcaa0cf36bf3477a8d16900aa01f73fa63f93d9028aed4ef047cc15da45c5384e097f5cd30226c8a2abf245a83863d35f3cd",
          "sha256": "01ac85331005905833de73a95a498c79ec93c973de7770a17a8eee9696c84f42",
          "sha1": "155cd2c28e2521bb5a69bfc1197adda593a3b5ab",
          "md5": "bb0788656d37ea3bce7c88c7e1872aea"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-debug.aar",
          "url": "mealz-shared-analytics-android-debug-4.2.0.aar",
          "size": 46746,
          "sha512": "7db562eee8d3801495118502b212bcaa0cf36bf3477a8d16900aa01f73fa63f93d9028aed4ef047cc15da45c5384e097f5cd30226c8a2abf245a83863d35f3cd",
          "sha256": "01ac85331005905833de73a95a498c79ec93c973de7770a17a8eee9696c84f42",
          "sha1": "155cd2c28e2521bb5a69bfc1197adda593a3b5ab",
          "md5": "bb0788656d37ea3bce7c88c7e1872aea"
        }
      ]
    }
  ]
}
