{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.8.0/mealz-shared-analytics-4.8.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.8.0.klib",
          "size": 58235,
          "sha512": "292694d9cf29659eded2fa9b313eb1142eacb31cfa562e4a3751f13db2889a5d9fe91fcbe61b08f04d80c1e5492132f8d9c2ccbe0107c7ec04c37bf5bac78c24",
          "sha256": "36def7ab6e59c68b2d720b42259b377191cbe20eade61164d1a454f1b39fb259",
          "sha1": "d524294cd050760ff8c5ac1e9a4f31ad83e92fff",
          "md5": "853632b6a6dfe33482f1e3ddf166dee9"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.8.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.8.0-metadata.jar",
          "size": 4925,
          "sha512": "cd69f803aadba2d58a526862018b54ec8d84c193fd63bc351194d4bc6ec0b095c35001e20ada609f4dacf6abef2f1d7543a498876ab94ee0005db5b0b646c39f",
          "sha256": "911a8d99bfc84c55457dbb6d1f68d46973b7f4a1569952f261751d927b74d7ba",
          "sha1": "c8606b90cd6f7a739e3a0d6edf6d788f5a4d8d22",
          "md5": "b425a8fed5d688ee10d8ed4cff491a0e"
        }
      ]
    }
  ]
}
