{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.1/mealz-shared-analytics-4.3.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.3.1.klib",
          "size": 54489,
          "sha512": "02696e4c4db84ede171ec1a41adbfee1c5b63c940ccb64951d7cfcdf107031abaf88c1a27264faa9d6842f7b30573e224cb51f73eae441aa30effdf2c56e6be4",
          "sha256": "545db6167c89d77dc5d3bdd15200dc0f6cc39e32479931c524fc2e10b3c29962",
          "sha1": "53ed7a5b4a4bbf9141e150a0cc078449090eb358",
          "md5": "f74d1addafada35d0a1c0cff07082008"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.3.1-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.3.1-metadata.jar",
          "size": 4911,
          "sha512": "0225d5e427d330d0d2722a81d0cdf54bc66cc18e380fdb8e529eeac0c0f4cabed212a4fd959c1905a42bf701c76b1501e7a0264ef241de2c3c9cfb3dbe886c52",
          "sha256": "8f24e1dc822401a0a080963354ed59dcd1eed49a85a7f7d1e849930adc6689c8",
          "sha1": "028b07c16d7c790eb387180fb265ca60733b0aaa",
          "md5": "fdbb136f4194a50ea7e0ce21f5c7f361"
        }
      ]
    }
  ]
}
