{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.15.0/mealz-shared-analytics-4.15.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.15.0.klib",
          "size": 58893,
          "sha512": "cd98ecf045543d2cf55b93dcaf602a38a8120642a961de158f4f17970ecccc7f9b3031ef2a123e8fb3f891af98ac924bc14ce05234159eeedcdc8ab38ef5ff7c",
          "sha256": "7c12f7222aa286a7af019ef9c4f66a9f2c92c58cb35de3af33bd6452437d10ee",
          "sha1": "c91ea55cde8f43a5c5aea830d1fca77c1d61e7b4",
          "md5": "454b5a65e15cf210cd5e3d3fd6f36cf1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.15.0-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.15.0-metadata.jar",
          "size": 4925,
          "sha512": "926733be9797534667dc8f3456104b0ce9d90448ab466d01a0076cfea27dfb79d95646ea07e6b3865d40f7bc8f2788d2205b3f3e071abcc9c75ac30832446b03",
          "sha256": "a59613516eff0155823794d99cf5f6fc6440fe41d5419bfea367c45781ce543d",
          "sha1": "12b6a3d9a1218660dee621489d49b47ceb7b3552",
          "md5": "2745d109cd4990584f9ec759594396fd"
        }
      ]
    }
  ]
}
