{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.1/mealz-shared-analytics-4.3.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.3.1.klib",
          "url": "mealz-shared-analytics-js-4.3.1.klib",
          "size": 53774,
          "sha512": "6c74a3078e8e678630c154970dcd32bb4d736544d76447c9b1a9f9d17212fd19eba936aa495fa1e9e5e01b55a1c3766edb886e125ff6992da714f5bba3f72e1d",
          "sha256": "4dc8ea604fa613cc00c7fbc637bf8b4fae9a045239a4e0ab574dd65122976efb",
          "sha1": "e9ef5f2654aea2d89b1a39adad643b68f426e929",
          "md5": "173e820d5eebba12744f553337fc540e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.3.1.klib",
          "url": "mealz-shared-analytics-js-4.3.1.klib",
          "size": 53774,
          "sha512": "6c74a3078e8e678630c154970dcd32bb4d736544d76447c9b1a9f9d17212fd19eba936aa495fa1e9e5e01b55a1c3766edb886e125ff6992da714f5bba3f72e1d",
          "sha256": "4dc8ea604fa613cc00c7fbc637bf8b4fae9a045239a4e0ab574dd65122976efb",
          "sha1": "e9ef5f2654aea2d89b1a39adad643b68f426e929",
          "md5": "173e820d5eebba12744f553337fc540e"
        }
      ]
    }
  ]
}
