{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.11.0/mealz-shared-analytics-4.11.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.11.0.klib",
          "size": 58357,
          "sha512": "16217bd52760faa3526cfa8520d7c6a4c27cb6d94f4b8aa7cd40a0679c07af71559d238e7757e8f015310dfa6ba72102ef63b1abf9d28a6a15ee897fd0328c8c",
          "sha256": "575ad1f67dc8be5a6e5bd3df7e4222fe61c90c12efb73bac9f3597928356f699",
          "sha1": "7dbc898cc4a8b1c7e2c8c8d5c6da79800f842d57",
          "md5": "47c66a5799a356a090d1c1c1a8d6916a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.11.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.11.0-metadata.jar",
          "size": 4925,
          "sha512": "f348edd944e9e221e9a98d77c96cb11c08ff8d1b72fbbdf0a511697e1a306ef9e99df63d53e20f9b251536bf3c0b21979d15af258b60b1b07dd1c14d6ca48101",
          "sha256": "6a08d839cd591b332ed00dad302b26162b0b3b2b02f4478fa794b057dda3aa04",
          "sha1": "079834ceb74adb1e276469d67a4006e1f7a8d5ca",
          "md5": "f4d9219a2cb0c821f4268b2b76ea8fc8"
        }
      ]
    }
  ]
}
