{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.1.0/mealz-shared-analytics-4.1.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.1.0.klib",
          "size": 53092,
          "sha512": "0b434354af93a5c8aaf4388b666d9c53e676a9f4903e0a8cc7f887eee813d062939bb18659f84dcdcf2a5ae74c427440ce4da217069e80283207c82eafe9a82b",
          "sha256": "5c9790f7bf9f6cdd14230e9bd3a01ae7f0e254d8ee1250bb2ea57bcbddbb4709",
          "sha1": "7469aa819195bc413da689c19beede81c80e2e1d",
          "md5": "35e7d96a14990474a36334dacfc53608"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.1.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.1.0-metadata.jar",
          "size": 4911,
          "sha512": "26c5d444f84bbb4fe828b535a749ff246bf763ee892d30f0607448c4d117b02d79a333379a7c0d8b1e95addb47e7ad71dd4824a07d7308e4f45902e08a8f04d1",
          "sha256": "fec2bda8d5ef5549512f533164fda26ae858a34ba8f80fc355ac0962367684ee",
          "sha1": "c1bcd39553cd9f555d79bcb944631c1301cca1d1",
          "md5": "b413207a0114d9c6b634a012b3d67d96"
        }
      ]
    }
  ]
}
