{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.5.0/mealz-shared-analytics-4.5.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.5.0.klib",
          "size": 55530,
          "sha512": "fa4fdf08bb48d97fc8a2f9214dd086e8af4a0a478251168b753b8f0b5e0a49151fe66358cccab7d24ab4fa80e8f29bb7259c3a944fc09aa1621d7eb358c30136",
          "sha256": "cdb882cb48b80f9437a7c86b8121892a263e1bd95a11badc8bd360dedfe8bfe6",
          "sha1": "fb469ab550481cc4d053ae179ee1c812385dc527",
          "md5": "e97a312f516b4e80791d6d1bd1279816"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.5.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.5.0-metadata.jar",
          "size": 4911,
          "sha512": "5e6e6f7efce9fb96e37b4b3a19dab8a0ac36b826c206f78526dd6d5a76189f7cd1b6408fa8ff2f3925c6f6f69804fc29458154be6a73dcce32c488800f120d42",
          "sha256": "8704e1e6fc3b73f34aa2f04ed6234196d2ea57f61edaa553d8734ed321e1454b",
          "sha1": "60f08a9d7783a0df2a75552a79d481e8b1c8c478",
          "md5": "7fe607f217caa2903f2142d060d1e57c"
        }
      ]
    }
  ]
}
