{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.8.0/mealz-shared-analytics-4.8.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.8.0.klib",
          "url": "mealz-shared-analytics-js-4.8.0.klib",
          "size": 57317,
          "sha512": "f92d4950ca449812ece5d5fea524bc11acb66cc271fee8bceace169eb7da19b4b92a549327a9b5139c9175ba510fcd88df062c9f9a9770fe26419b0c493cd738",
          "sha256": "0ec0224e48c1c5852ac2435097c6723d4b1e8af62e06e7896d0ed16c950b6479",
          "sha1": "5bd90e691026f8f9310c4329b9164d6f32dcdf94",
          "md5": "07b88fc6c53871cebe0e256b003d0ae2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.8.0.klib",
          "url": "mealz-shared-analytics-js-4.8.0.klib",
          "size": 57317,
          "sha512": "f92d4950ca449812ece5d5fea524bc11acb66cc271fee8bceace169eb7da19b4b92a549327a9b5139c9175ba510fcd88df062c9f9a9770fe26419b0c493cd738",
          "sha256": "0ec0224e48c1c5852ac2435097c6723d4b1e8af62e06e7896d0ed16c950b6479",
          "sha1": "5bd90e691026f8f9310c4329b9164d6f32dcdf94",
          "md5": "07b88fc6c53871cebe0e256b003d0ae2"
        }
      ]
    }
  ]
}
