{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/3.0.0/mealz-shared-analytics-3.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-3.0.0.klib",
          "size": 53464,
          "sha512": "d4170a8c99115774de313d7f2b42ecea59bfa85b664d1d376ac22def318260d8813b128ed63c4d47680a7c3bf92a06b29357a225a4c9c2663810b0c22fa8734c",
          "sha256": "895cea249207e1750d4cb1444458a695100fee0d3cd9cd4e3bbca540a4fc9d5a",
          "sha1": "d2a02355c402ed4e0018143f0007f8091cba190a",
          "md5": "57223ecd5f9782c71b984b506d561962"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-3.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-3.0.0-metadata.jar",
          "size": 4911,
          "sha512": "2a3fe666c6ce526e265bee3b35ab640fa099ce1bb4bccbcce0ff5d204f18995a3016ccafbf33b2a991a919b3a563d2ed4d34f679cc0abfb4fd249fe6210a3c80",
          "sha256": "ef520c24f781d11e4eff9bce2d030033322bba3379fd90f8c2e196b5bd34ca8c",
          "sha1": "126b49aab20c5b02cb232a6ece63525b47bd5e44",
          "md5": "eecbc1133bafc5747590ed59971027af"
        }
      ]
    }
  ]
}
