{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.14.0/mealz-shared-analytics-4.14.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.14.0.klib",
          "size": 58688,
          "sha512": "a978fccc2f0888bf1f36b462d2978432cdab0b1415c2d0b3688fa740eb5475e2c5e5afc1fa8dab897ba4e2e6a62e3f8dcd9f8a4876e6ed402bc11ec402993790",
          "sha256": "2f6602253bd66873288403ed4bc95f64f4323ad1f7263819d0c7ca73c70da9a4",
          "sha1": "131f54850ed7a1f4d3416ebbe2764682a63fb421",
          "md5": "bb01f671f434fe3e28792fc86532592b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.14.0-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.14.0-metadata.jar",
          "size": 4925,
          "sha512": "c5d5ae6d6a78237d58fa7d1e0c658cdac7d26340e482d1e2dce489d3baae862c864b3b0ee8d40f19de7d3b045c51fdf610a5442e0b4eff2c3d072bda070008d4",
          "sha256": "0234b0694edff1def6661c7b76dae756d83a4281d16ba7f2db96609bbef1f8e1",
          "sha1": "78e263724cc81523268b1b645b18f914be0ead0e",
          "md5": "0896b7bee525b41cd86ab0410563a78f"
        }
      ]
    }
  ]
}
